---
# Defaults for k3d role

# Install settings
k3d_version: v5.8.3
k3d_os_map:
  Linux: linux
k3d_arch_map:
  x86_64: amd64
  aarch64: arm64
  arm64: arm64
k3d_os: "{{ k3d_os_map.get(ansible_system, 'linux') }}"
k3d_arch: "{{ k3d_arch_map.get(ansible_architecture, 'amd64') }}"
k3d_install_path: /usr/local/bin/k3d

# Cluster settings
k3d_cluster_name: tech-ward
k3d_servers: 1
