---
- name: Create whoami deployment
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: whoami
        namespace: "{{ whoami_namespace }}"
      spec:
        replicas: 2
        selector:
          matchLabels:
            app: whoami
        template:
          metadata:
            labels:
              app: whoami
          spec:
            containers:
              - name: whoami
                image: traefik/whoami
                ports:
                  - containerPort: 80

- name: Create whoami service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: whoami
        namespace: "{{ whoami_namespace }}"
      spec:
        ports:
          - port: 80
        selector:
          app: whoami

- name: Create whoami ingress route
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: traefik.io/v1alpha1
      kind: IngressRoute
      metadata:
        name: whoami
        namespace: "{{ whoami_namespace }}"
      spec:
        entryPoints:
          - web
        routes:
          - match: Host(`whoami.localhost`)
            kind: Rule
            services:
              - name: whoami
                port: 80
