# Helm: https://helm.sh/docs/intro/install/#from-script
- name: Download Helm installation script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: "0700"
    # mode: '0755'

- name: Run Helm installation script
  command: /tmp/get_helm.sh
  args:
    creates: /usr/local/bin/helm
  register: helm_install_result
  changed_when: false

- name: Add /usr/local/bin to PATH
  lineinfile:
    path: /home/{{ project_user }}/.bashrc
    line: "export PATH=$PATH:/usr/local/bin"
  when:
    - helm_install_result is defined
    - helm_install_result.rc == 0
